version: '3'

services:
  desmosnode0:
    container_name: desmosnode0
    image: "desmoslabs/desmos"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-desmosd.log}
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  desmosnode1:
    container_name: desmosnode1
    image: "desmoslabs/desmos"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-desmosd.log}
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  desmosnode2:
    container_name: desmosnode2
    image: "desmoslabs/desmos"
    environment:
      - ID=2
      - LOG=${LOG:-desmosd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  desmosnode3:
    container_name: desmosnode3
    image: "desmoslabs/desmos"
    environment:
      - ID=3
      - LOG=${LOG:-desmosd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.10.0/16
