version: '3'

services:
  desmosdnode0:
    container_name: desmosdnode0
    image: "desmos-labs/desmosdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-desmosd.log}
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  desmosdnode1:
    container_name: desmosdnode1
    image: "desmos-labs/desmosdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-desmosd.log}
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  desmosdnode2:
    container_name: desmosdnode2
    image: "desmos-labs/desmosdnode"
    environment:
      - ID=2
      - LOG=${LOG:-desmosd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  desmosdnode3:
    container_name: desmosdnode3
    image: "desmos-labs/desmosdnode"
    environment:
      - ID=3
      - LOG=${LOG:-desmosd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/desmosd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.10.0/16
