name: Benchmarks
on:
  pull_request:
  push:
    branches:
      - master
env:
  GO111MODULE: "on"
jobs:
  Benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go ğŸ§°
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.15

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Go cache ğŸ’¾
        uses: actions/cache@v2
        with:
          path: ~/go/pkg
          key: ${{ runner.os }}-go-pkg-${{ hashFiles('**/go.mod') }}

      - name: Restore benchstat ğŸª›
        uses: actions/cache@v2.1.7
        with:
          path: ~/go/bin/benchstat
          key: ${{ runner.os }}-benchstat

      - name: Restore base benchmark result ğŸ“
        uses: actions/cache@v2
        with:
          path: |
            bench-master.txt
          # Using base sha for PR or new commit hash for master/main push in benchmark result key.
          key: ${{ runner.os }}-bench-${{ (github.event.pull_request.base.sha != github.event.after) && github.event.pull_request.base.sha || github.event.after }}

      - name: Benchmark ğŸ§®
        run: REF_NAME=${GITHUB_REF##*/} make benchmark